stages:
  - security scans
  - setup and deploy

variables:
   AWS_DEFAULT_REGION: "us-east-1"

security scans:
  stage: unit test and security scans
  image: python:3.9
  before_script:
    - echo "Installing Update..."
    - apt-get update
    - apt-get install -y nodejs npm
    - npm install -g snyk
    - snyk auth $SNYK_TOKEN
  script:
    - snyk iac test --report || echo "Snyk found vulnerabilities!"
  

setup & deploy:
  stage: setup and deploy
  image: ruby:3.1
  before_script:
    - echo "Setting up for deployment..."
    - apt-get update && apt-get install -y wget unzip
    - curl --proto '=https' --tlsv1.2 -fsSL https://get.opentofu.org/install-opentofu.sh -o install-opentofu.sh
    - chmod +x install-opentofu.sh
    - ./install-opentofu.sh --install-method standalone
    - echo "Setting up AWS credentials..."
    - mkdir -p ~/.aws/
    - echo "[default]" > ~/.aws/credentials
    - echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> ~/.aws/credentials
    - echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials
  script:
    - echo "Initializing tofu code..."
    - tofu init
    - echo "Validating tofu code..."
    - tofu validate
    - echo "Generating tofu plan..."
    - tofu plan
    - echo "Applying tofu code..."
    - tofu apply -auto-approve
