---
apiVersion: v1
kind: Service
metadata:
  name: golang-test-app
  annotations:
    zarf.dev/connect-description: "Your test golang app is running!!!"
    zarf.dev/connect-url: "?golangapp"
  labels:
    # Enables "zarf connect doom"
    zarf.dev/connect-name: golangapp
spec:
  selector:
    app: golang-test-app
  ports:
    - name: http
      port: 8000
      protocol: TCP
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: golang-test-app
  annotations:
    zarf.dev/connect-description: "Check out the golang-test-apps"
  labels:
    # Enables "zarf connect golang-test-apps"
    zarf.dev/connect-name: golang-test-apps
spec:
  selector:
    app: golang-test-app
  ports:
    - name: http
      port: 8000
      protocol: TCP
      targetPort: 8080