---
- name: Configure master node
  hosts: master_server
  become: yes
  tasks:
    
    - name: Update apt-get(yum in centos) repository
      apt:
        update_cache: yes

    - name: Execute the script to install brew and docker
      ansible.builtin.script: ./scripts/script.sh

    - name: Execute the script to install UDS Cli, Zarf, K3d, Kubectl and K9s using Homebrew and deploy UDS Core
      ansible.builtin.script: ./scripts/script2.sh